<a href="https://colab.research.google.com/github/leoschmoll/Excel-Project/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting to 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

select table_name
from information_schema.tables
where table_schema = 'public';

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [22]:
%%sql

SELECT
s.orderdate,
s.quantity * s.netprice * s.exchangerate AS net_revenue,
c.givenname,
c.surname,
c.countryfull,
c.continent,
p.productkey,
p.productname,
p.categoryname,
p.subcategoryname,
case
  when s.quantity * s.netprice * s.exchangerate > 1000 then 'HIGH'
  else 'LOW'
end as high_low
FROM sales s
left join customer c
  on s.customerkey = c.customerkey
left join product p
  on s.productkey = p.productkey
where
 orderdate::DATE = '2020-01-01'
;

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

113 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,LOW
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,LOW
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",LOW
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,HIGH
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,LOW
...,...,...,...,...,...,...,...,...,...,...,...
108,2020-01-01,3756.97,Sheron,Gilbert,United States,North America,2007,Fabrikam Microwave 1.5CuFt X1100 Black,Home Appliances,Microwaves,HIGH
109,2020-01-01,1948.32,Sheron,Gilbert,United States,North America,419,Adventure Works Desktop PC1.80 ED180 Silver,Computers,Desktops,HIGH
110,2020-01-01,7465.31,Sheron,Gilbert,United States,North America,152,"Adventure Works 40"" LCD HDTV M690 Brown",TV and Video,Televisions,HIGH
111,2020-01-01,803.65,Sheron,Gilbert,United States,North America,156,"Adventure Works 26"" 720p LCD HDTV M140 Brown",TV and Video,Televisions,LOW
112,2020-01-01,178.20,Earl,Montiel,United States,North America,471,Proseware LCD15 E103 Black,Computers,Monitors,LOW